#!/usr/bin/env python3
"""
Regenerate Chapter 6 transcript from source PDF.

Usage (in the repo, inside the recommended venv):

/venv/path/bin/python notes/class 12/Ch6_Evolution/regenerate_transcript.py \
    --pdf "Chapter/class 12/Chapter 6 - Evolution.pdf" \
    --out chapter_6_evolution.md

What it does:
- Opens the source PDF with pdfplumber and extracts page-wise text.
- Performs lightweight cleanup (collapse repeated blank lines).
- Emits a Markdown transcript file suitable to commit back to the repo.

Notes:
- This script does NOT extract or embed figures. It only regenerates the text transcript.
- Run it from the repo root so paths resolve as written.

Requirements:
- pdfplumber

"""
import argparse
import os
import re
import sys

try:
    import pdfplumber
except Exception as e:
    print("Missing dependency: pdfplumber. Install into your venv and re-run. Error:", e)
    sys.exit(2)


def normalize_whitespace(s: str) -> str:
    # Collapse repeated blank lines to two, strip trailing spaces on lines
    lines = [ln.rstrip() for ln in s.splitlines()]
    out_lines = []
    blank_run = 0
    for ln in lines:
        if ln.strip() == "":
            blank_run += 1
            if blank_run <= 2:
                out_lines.append("")
        else:
            blank_run = 0
            out_lines.append(ln)
    return "\n".join(out_lines).strip() + "\n"


def extract_text(pdf_path: str) -> str:
    if not os.path.exists(pdf_path):
        raise FileNotFoundError(f"PDF not found at: {pdf_path}")
    parts = []
    with pdfplumber.open(pdf_path) as pdf:
        for i, page in enumerate(pdf.pages, start=1):
            try:
                text = page.extract_text() or ""
            except Exception:
                # fallback: extract words joined by spaces
                words = page.extract_words()
                text = " ".join(w.get('text','') for w in words)
            header = f"<!-- Page {i} -->\n\n"
            parts.append(header + text + "\n\n")
    raw = "\n".join(parts)
    return normalize_whitespace(raw)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--pdf", required=True, help="relative path to source PDF in repo")
    p.add_argument("--out", required=True, help="output markdown path (written/overwritten)")
    args = p.parse_args()

    pdf_path = args.pdf
    out_path = args.out

    print(f"Extracting text from: {pdf_path}")
    text = extract_text(pdf_path)

    # Minimal top matter: try to pull chapter title from first page first line
    first_line = text.splitlines()[0] if text.splitlines() else ''
    md_top = []
    md_top.append(f"# Regenerated transcript — source: {os.path.basename(pdf_path)}\n")
    md_top.append("<!-- THIS FILE WAS GENERATED by regenerate_transcript.py; review before committing -->\n")
    md_top.append("\n")

    out_md = "\n".join(md_top) + text

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(out_md)

    print(f"Wrote transcript to: {out_path}")

if __name__ == '__main__':
    main()
